# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget nrf::test_serial_port_enum_sd_api_v2 nrf::test_sd_api_v2 nrf::test_sd_api_v3 nrf::test_sd_api_v5 nrf::test_sd_api_v6 nrf::heart_rate_monitor_sd_api_v2 nrf::heart_rate_monitor_sd_api_v3 nrf::heart_rate_monitor_sd_api_v5 nrf::heart_rate_monitor_sd_api_v6 nrf::heart_rate_collector_sd_api_v2 nrf::heart_rate_collector_sd_api_v3 nrf::heart_rate_collector_sd_api_v5 nrf::heart_rate_collector_sd_api_v6 nrf::nrf_ble_driver_sd_api_v2_shared nrf::nrf_ble_driver_sd_api_v2_static nrf::nrf_ble_driver_sd_api_v3_shared nrf::nrf_ble_driver_sd_api_v3_static nrf::nrf_ble_driver_sd_api_v5_shared nrf::nrf_ble_driver_sd_api_v5_static nrf::nrf_ble_driver_sd_api_v6_shared nrf::nrf_ble_driver_sd_api_v6_static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target nrf::test_serial_port_enum_sd_api_v2
add_executable(nrf::test_serial_port_enum_sd_api_v2 IMPORTED)

# Create imported target nrf::test_sd_api_v2
add_executable(nrf::test_sd_api_v2 IMPORTED)

# Create imported target nrf::test_sd_api_v3
add_executable(nrf::test_sd_api_v3 IMPORTED)

# Create imported target nrf::test_sd_api_v5
add_executable(nrf::test_sd_api_v5 IMPORTED)

# Create imported target nrf::test_sd_api_v6
add_executable(nrf::test_sd_api_v6 IMPORTED)

# Create imported target nrf::heart_rate_monitor_sd_api_v2
add_executable(nrf::heart_rate_monitor_sd_api_v2 IMPORTED)

# Create imported target nrf::heart_rate_monitor_sd_api_v3
add_executable(nrf::heart_rate_monitor_sd_api_v3 IMPORTED)

# Create imported target nrf::heart_rate_monitor_sd_api_v5
add_executable(nrf::heart_rate_monitor_sd_api_v5 IMPORTED)

# Create imported target nrf::heart_rate_monitor_sd_api_v6
add_executable(nrf::heart_rate_monitor_sd_api_v6 IMPORTED)

# Create imported target nrf::heart_rate_collector_sd_api_v2
add_executable(nrf::heart_rate_collector_sd_api_v2 IMPORTED)

# Create imported target nrf::heart_rate_collector_sd_api_v3
add_executable(nrf::heart_rate_collector_sd_api_v3 IMPORTED)

# Create imported target nrf::heart_rate_collector_sd_api_v5
add_executable(nrf::heart_rate_collector_sd_api_v5 IMPORTED)

# Create imported target nrf::heart_rate_collector_sd_api_v6
add_executable(nrf::heart_rate_collector_sd_api_v6 IMPORTED)

# Create imported target nrf::nrf_ble_driver_sd_api_v2_shared
add_library(nrf::nrf_ble_driver_sd_api_v2_shared SHARED IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v2_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v2"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v2_static
add_library(nrf::nrf_ble_driver_sd_api_v2_static STATIC IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v2_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v2"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v3_shared
add_library(nrf::nrf_ble_driver_sd_api_v3_shared SHARED IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v3_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v3"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v3_static
add_library(nrf::nrf_ble_driver_sd_api_v3_static STATIC IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v3_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v3"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v5_shared
add_library(nrf::nrf_ble_driver_sd_api_v5_shared SHARED IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v5_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v5"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v5_static
add_library(nrf::nrf_ble_driver_sd_api_v5_static STATIC IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v5_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v5"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v6_shared
add_library(nrf::nrf_ble_driver_sd_api_v6_shared SHARED IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v6_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v6"
)

# Create imported target nrf::nrf_ble_driver_sd_api_v6_static
add_library(nrf::nrf_ble_driver_sd_api_v6_static STATIC IMPORTED)

set_target_properties(nrf::nrf_ble_driver_sd_api_v6_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/sd_api_v6"
)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/nrf-ble-driverTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
